In [1]:
import pandas as pd

In [2]:
Path = "doctors_per_zip.csv"

In [3]:
df = pd.read_csv(Path)

# COLUMNS NAME WITH DESCRIPTION 

# NPI - Unique clinician ID assigned by NPPES
# Ind_PAC_ID - Unique individual clinician ID assigned by PECOS
# Ind_enrl_ID - Unique ID for the clinician enrollment that is the source for the data in the observation 
# Provider Last Name - Individual clinician last name 
# 'Provider First Name' - Individual clinician first name
# 'Provider Middle Name'- Individual clinician middle name
# 'suff' - Individual clinician suffix
# 'gndr' - Individual clinician gender
# 'Cred' - Medical credential such as MD, DO, DPM, etc. 
# 'Med_sch' - Individual clinician’s medical school 
# 'Grd_yr' - Individual clinician’s medical school graduation year
#'pri_spec' - Primary medical specialty reported by the individual clinician in the selected enrollment 
# 'sec_spec_1' - First secondary medical specialty reported by the individual clinician in the selected enrollment
# 'sec_spec_2' - Second secondary medical specialty reported by the individual clinician in the selected enrollment
# 'sec_spec_3' - Third secondary medical specialty reported by the individual clinician in the selected enrollment
# 'sec_spec_4' - Fourth secondary medical specialty reported by the individual clinician in the selected enrollment
# 'sec_spec_all' - All secondary medical specialty reported by the individual clinician in the selected enrollment

# 'Telehlth' - Indicator for whether clinician offers telehealth services over video and/or audio
#  Y = Medicare fee-for-service claims indicate that clinician offers telehealth services

# 'Facility Name' - Legal organization name of the group practice that the individual clinician works with – will 
# be blank if the address is not linked to a group

# 'org_pac_id' - - Unique group ID assigned by PECOS to the group that the individual clinician works with – will 
# be blank if the address is not linked to a group

# 'num_org_mem'- Total number of individual clinicians affiliated with the group based on Group Practice PAC ID
# 'adr_ln_1'- Group or individual's line 1 address 
# 'adr_ln_2' - Group or individual's line 2 address
# 'ln_2_sprs' - Marker that the address as reported may be incomplete 
# 'City/Town' - Group or individual's city 
# 'State' - Group or individual's state
# 'ZIP Code' - Group or individual's ZIP code (9 digits when available
# 'Telephone Number' - Phone number is listed only when there is a single phone number available for the address

# 'ind_assgn' - Indicator for whether clinician accepts Medicare approved amount as payment in full Y = Clinician 
# accepts Medicare approved amount as payment in full M = Clinician may accept Medicare Assignment

# 'grp_assgn' - Indicator for whether group accepts Medicare approved amount as payment in full Y = Group accepts 
# Medicare approved amount as payment in full M = Group may accept Medicare Assignment

# 'adrs_id'- Unique identifier for the practice location; offices within the same building, but varied by suite or 
# floor, will havethe same Address ID aside from the final two characters

In [4]:
df.head()

,NPI,Ind_PAC_ID,Ind_enrl_ID,Provider Last Name,Provider First Name,Provider Middle Name,suff,gndr,Cred,Med_sch,...,adr_ln_1,adr_ln_2,ln_2_sprs,City/Town,State,ZIP Code,Telephone Number,ind_assgn,grp_assgn,adrs_id
0,1003829771,8628019098,I20180710001015,MEANEY,PETER,ANDREW,NaN,M,MD,OTHER,...,725 WELCH RD,NaN,NaN,PALO ALTO,CA,943041601,6.504987e+09,Y,Y,CA943041601PA725XXRDXX300
1,1013128297,5496845950,I20071220000361,BRONSTEIN,DAVID,E,NaN,M,MD,"UNIVERSITY OF CALIFORNIA, SAN DIEGO SCHOOL OF ...",...,13652 CANTARA ST,NaN,NaN,PANORAMA CITY,CA,914025423,8.183752e+09,Y,Y,CA914025423PA13652STXX300
2,1013128297,5496845950,I20071220000361,BRONSTEIN,DAVID,E,NaN,M,MD,"UNIVERSITY OF CALIFORNIA, SAN DIEGO SCHOOL OF ...",...,43112 15TH ST W,NaN,NaN,LANCASTER,CA,935346219,6.617262e+09,Y,Y,CA935346219LA43112WXXX400
3,1013128297,5496845950,I20071220000361,BRONSTEIN,DAVID,E,NaN,M,MD,"UNIVERSITY OF CALIFORNIA, SAN DIEGO SCHOOL OF ...",...,4502 E AVE S,NaN,NaN,PALMDALE,CA,935524480,6.615538e+09,Y,Y,CA935524480PA4502XSXXX400
4,1013907377,8022146182,I20100511000326,BAKER,MARNIE,NaN,NaN,F,MD,TULANE UNIVERSITY SCHOOL OF MEDICINE,...,4050 BARRANCA PKWY,SUITE 200,NaN,IRVINE,CA,926041723,9.495511e+09,Y,Y,CA926041723IR4050XPKWY303

In [5]:
df.columns

Index(['NPI', 'Ind_PAC_ID', 'Ind_enrl_ID', 'Provider Last Name',
       'Provider First Name', 'Provider Middle Name', 'suff', 'gndr', 'Cred',
       'Med_sch', 'Grd_yr', 'pri_spec', 'sec_spec_1', 'sec_spec_2',
       'sec_spec_3', 'sec_spec_4', 'sec_spec_all', 'Telehlth', 'Facility Name',
       'org_pac_id', 'num_org_mem', 'adr_ln_1', 'adr_ln_2', 'ln_2_sprs',
       'City/Town', 'State', 'ZIP Code', 'Telephone Number', 'ind_assgn',
       'grp_assgn', 'adrs_id'],
      dtype='object')

In [6]:
columns_to_select = ['NPI','Ind_enrl_ID', 'Provider Last Name', 'Provider First Name', 'Provider Middle Name', 'gndr', 'pri_spec', 'sec_spec_all', 'Telehlth', 'Facility Name','City/Town', 'State', 'ZIP Code']
df2 = df[columns_to_select]
df2.head()

,NPI,Ind_enrl_ID,Provider Last Name,Provider First Name,Provider Middle Name,gndr,pri_spec,sec_spec_all,Telehlth,Facility Name,City/Town,State,ZIP Code
0,1003829771,I20180710001015,MEANEY,PETER,ANDREW,M,PEDIATRIC MEDICINE,NaN,NaN,LPCH MEDICAL GROUP DIV OF LUCILE,PALO ALTO,CA,943041601
1,1013128297,I20071220000361,BRONSTEIN,DAVID,E,M,PEDIATRIC MEDICINE,INFECTIOUS DISEASE,NaN,SOUTHERN CALIFORNIA PERMANENTE MEDICAL GROUP,PANORAMA CITY,CA,914025423
2,1013128297,I20071220000361,BRONSTEIN,DAVID,E,M,PEDIATRIC MEDICINE,INFECTIOUS DISEASE,NaN,SOUTHERN CALIFORNIA PERMANENTE MEDICAL GROUP,LANCASTER,CA,935346219
3,1013128297,I20071220000361,BRONSTEIN,DAVID,E,M,PEDIATRIC MEDICINE,INFECTIOUS DISEASE,NaN,SOUTHERN CALIFORNIA PERMANENTE MEDICAL GROUP,PALMDALE,CA,935524480
4,1013907377,I20100511000326,BAKER,MARNIE,NaN,F,PEDIATRIC MEDICINE,NaN,NaN,MEMORIALCARE MEDICAL FOUNDATION,IRVINE,CA,926041723

In [7]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 879 entries, 0 to 878
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   NPI                   879 non-null    int64
 1   Ind_enrl_ID           879 non-null    object
 2   Provider Last Name    879 non-null    object
 3   Provider First Name   879 non-null    object
 4   Provider Middle Name  594 non-null    object
 5   gndr                  879 non-null    object
 6   pri_spec              879 non-null    object
 7   sec_spec_all          382 non-null    object
 8   Telehlth              105 non-null    object
 9   Facility Name         833 non-null    object
 10  City/Town             879 non-null    object
 11  State                 879 non-null    object
 12  ZIP Code              879 non-null    int64
dtypes: int64(2), object(11)
memory usage: 89.4+ KB

In [8]:
duplicats = df2.duplicated()
duplicats.sum()

62

In [9]:
df2[df2.duplicated()]

,NPI,Ind_enrl_ID,Provider Last Name,Provider First Name,Provider Middle Name,gndr,pri_spec,sec_spec_all,Telehlth,Facility Name,City/Town,State,ZIP Code
27,1043402332,I20101008000138,KUO,CAROLINE,NaN,F,PEDIATRIC MEDICINE,NaN,Y,UC REGENTS,LOS ANGELES,CA,900950001
29,1043402332,I20101008000138,KUO,CAROLINE,NaN,F,PEDIATRIC MEDICINE,NaN,Y,UC REGENTS,LOS ANGELES,CA,900953075
102,1144323213,I20040420001670,SKLANSKY,MARK,S,M,PEDIATRIC MEDICINE,NaN,NaN,UC REGENTS,LOS ANGELES,CA,900953075
123,1164775623,I20190708002752,SRIVASTAVA,RACHANA,NaN,F,PEDIATRIC MEDICINE,NaN,NaN,UC REGENTS,LOS ANGELES,CA,900950001
125,1164775623,I20190708002752,SRIVASTAVA,RACHANA,NaN,F,PEDIATRIC MEDICINE,NaN,NaN,UC REGENTS,LOS ANGELES,CA,900953075
...,...,...,...,...,...,...,...,...,...,...,...,...,...
830,1952324022,I20140325002089,MARTINEZ,JULIAN,A,M,PEDIATRIC MEDICINE,MEDICAL GENETICS AND GENOMICS,NaN,UC REGENTS,LOS ANGELES,CA,900950001
832,1952324022,I20140325002089,MARTINEZ,JULIAN,A,M,PEDIATRIC MEDICINE,MEDICAL GENETICS AND GENOMICS,NaN,UC REGENTS,LOS ANGELES,CA,900953075
851,1972530988,I20060322000660,PERENS,GREGORY,S,M,PEDIATRIC MEDICINE,CARDIOVASCULAR DISEASE (CARDIOLOGY),NaN,UC REGENTS,LOS ANGELES,CA,900953075
854,1972600179,I20051205000789,MUELLER,LISA,A,F,PEDIATRIC MEDICINE,HEMATOLOGY/ONCOLOGY,NaN,SOUTHERN CALIFORNIA PERMANENTE MEDICAL GROUP,LOS ANGELES,CA,900276021
878,1992872717,I20101129001052,COOPER,ROBERT,M,M,PEDIATRIC MEDICINE,HEMATOLOGY/ONCOLOGY,NaN,SOUTHERN CALIFORNIA PERMANENTE MEDICAL GROUP,LOS ANGELES,CA,900276021

In [10]:
duplicates = df2[df2.duplicated(subset=['NPI', 'Ind_enrl_ID'], keep='first')]
duplicates

,NPI,Ind_enrl_ID,Provider Last Name,Provider First Name,Provider Middle Name,gndr,pri_spec,sec_spec_all,Telehlth,Facility Name,City/Town,State,ZIP Code
2,1013128297,I20071220000361,BRONSTEIN,DAVID,E,M,PEDIATRIC MEDICINE,INFECTIOUS DISEASE,NaN,SOUTHERN CALIFORNIA PERMANENTE MEDICAL GROUP,LANCASTER,CA,935346219
3,1013128297,I20071220000361,BRONSTEIN,DAVID,E,M,PEDIATRIC MEDICINE,INFECTIOUS DISEASE,NaN,SOUTHERN CALIFORNIA PERMANENTE MEDICAL GROUP,PALMDALE,CA,935524480
17,1033439898,I20160218001027,SESHADRI,ANURADHA,G,F,PEDIATRIC MEDICINE,INTERNAL MEDICINE,Y,THE REGENTS OF THE UNIVERSITY OF CALIFORNIA,WOODLAND HILLS,CA,913672362
22,1043233620,I20160815001236,WILLIAMS,TRACI,ANN,F,PEDIATRIC MEDICINE,NaN,NaN,PRIMARY MEDICAL GROUP OF VENTURA COUNTY INC,VENTURA,CA,930033214
25,1043328149,I20060510000209,CURRY,CYNTHIA,J,F,PEDIATRIC MEDICINE,MEDICAL GENETICS AND GENOMICS,Y,NaN,FRESNO,CA,937211365
...,...,...,...,...,...,...,...,...,...,...,...,...,...
866,1982765582,I20070710001031,FORT,GRADY,R,M,PEDIATRIC MEDICINE,NaN,NaN,"MCCLOUD HEALTHCARE CLINIC, INC.",MOUNT SHASTA,CA,960672137
873,1992725808,I20081110000429,TANEL,RONN,EL,M,PEDIATRIC MEDICINE,NaN,NaN,UNIVERSITY OF CALIFORNIA SAN FRANCISCO,SAN FRANCISCO,CA,941430810
875,1992857239,I20041105001029,FLORES,EDGAR,NaN,M,PEDIATRIC MEDICINE,INTERNAL MEDICINE,Y,NaN,MODESTO,CA,953502931
877,1992872717,I20101129001052,COOPER,ROBERT,M,M,PEDIATRIC MEDICINE,HEMATOLOGY/ONCOLOGY,NaN,SOUTHERN CALIFORNIA PERMANENTE MEDICAL GROUP,LOS ANGELES,CA,900276021
878,1992872717,I20101129001052,COOPER,ROBERT,M,M,PEDIATRIC MEDICINE,HEMATOLOGY/ONCOLOGY,NaN,SOUTHERN CALIFORNIA PERMANENTE MEDICAL GROUP,LOS ANGELES,CA,900276021

In [11]:
df2_cleaned = df2.drop_duplicates(subset=['NPI', 'Ind_enrl_ID'], keep='first')
df2_cleaned

,NPI,Ind_enrl_ID,Provider Last Name,Provider First Name,Provider Middle Name,gndr,pri_spec,sec_spec_all,Telehlth,Facility Name,City/Town,State,ZIP Code
0,1003829771,I20180710001015,MEANEY,PETER,ANDREW,M,PEDIATRIC MEDICINE,NaN,NaN,LPCH MEDICAL GROUP DIV OF LUCILE,PALO ALTO,CA,943041601
1,1013128297,I20071220000361,BRONSTEIN,DAVID,E,M,PEDIATRIC MEDICINE,INFECTIOUS DISEASE,NaN,SOUTHERN CALIFORNIA PERMANENTE MEDICAL GROUP,PANORAMA CITY,CA,914025423
4,1013907377,I20100511000326,BAKER,MARNIE,NaN,F,PEDIATRIC MEDICINE,NaN,NaN,MEMORIALCARE MEDICAL FOUNDATION,IRVINE,CA,926041723
5,1013912054,I20121009000156,SWENSSON,RICHARD,ERIC,M,PEDIATRIC MEDICINE,CARDIOVASCULAR DISEASE (CARDIOLOGY),NaN,CHILDREN'S HOSPITAL OF ORANGE COUNTY,ORANGE,CA,928684203
6,1013912674,I20141106000036,RECTO,MICHAEL,R,M,PEDIATRIC MEDICINE,CARDIOVASCULAR DISEASE (CARDIOLOGY),Y,CHILDREN'S HOSPITAL OF ORANGE COUNTY,ORANGE,CA,928684203
...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,1982997417,I20170710000954,PHAM,TRUNG,HOANG MINH,M,PEDIATRIC MEDICINE,INFECTIOUS DISEASE,NaN,LPCH MEDICAL GROUP DIV OF LUCILE,PALO ALTO,CA,943041601
871,1992091474,I20171113001510,SHAAHINFAR,ASHKON,NaN,M,PEDIATRIC MEDICINE,EMERGENCY MEDICINE,NaN,UCSF MEDICAL GROUP BUSINESS SERVICES,SAN FRANCISCO,CA,941432202
872,1992725808,I20081110000429,TANEL,RONN,EL,M,PEDIATRIC MEDICINE,NaN,NaN,UCSF MEDICAL GROUP BUSINESS SERVICES,SAN FRANCISCO,CA,941432202
874,1992857239,I20041105001029,FLORES,EDGAR,NaN,M,PEDIATRIC MEDICINE,INTERNAL MEDICINE,Y,NaN,FULLERTON,CA,928333207
876,1992872717,I20101129001052,COOPER,ROBERT,M,M,PEDIATRIC MEDICINE,HEMATOLOGY/ONCOLOGY,NaN,SOUTHERN CALIFORNIA PERMANENTE MEDICAL GROUP,LOS ANGELES,CA,900275822

In [12]:
missing_data = df2_cleaned.isnull().sum()
print(missing_data)

NPI                       0
Ind_enrl_ID               0
Provider Last Name        0
Provider First Name       0
Provider Middle Name    204
gndr                      0
pri_spec                  0
sec_spec_all            327
Telehlth                531
Facility Name            41
City/Town                 0
State                     0
ZIP Code                  0
dtype: int64

In [13]:
df2_cleaned = df2_cleaned.rename(columns={'gndr': 'Gender',
                                           'Telehlth': 'Telehealth',
                                            'pri_spec': 'Primary Specialty',
                                             'sec_spec_all': 'All Secondary Specialties'})
df2_cleaned.head()

,NPI,Ind_enrl_ID,Provider Last Name,Provider First Name,Provider Middle Name,Gender,Primary Specialty,All Secondary Specialties,Telehealth,Facility Name,City/Town,State,ZIP Code
0,1003829771,I20180710001015,MEANEY,PETER,ANDREW,M,PEDIATRIC MEDICINE,NaN,NaN,LPCH MEDICAL GROUP DIV OF LUCILE,PALO ALTO,CA,943041601
1,1013128297,I20071220000361,BRONSTEIN,DAVID,E,M,PEDIATRIC MEDICINE,INFECTIOUS DISEASE,NaN,SOUTHERN CALIFORNIA PERMANENTE MEDICAL GROUP,PANORAMA CITY,CA,914025423
4,1013907377,I20100511000326,BAKER,MARNIE,NaN,F,PEDIATRIC MEDICINE,NaN,NaN,MEMORIALCARE MEDICAL FOUNDATION,IRVINE,CA,926041723
5,1013912054,I20121009000156,SWENSSON,RICHARD,ERIC,M,PEDIATRIC MEDICINE,CARDIOVASCULAR DISEASE (CARDIOLOGY),NaN,CHILDREN'S HOSPITAL OF ORANGE COUNTY,ORANGE,CA,928684203
6,1013912674,I20141106000036,RECTO,MICHAEL,R,M,PEDIATRIC MEDICINE,CARDIOVASCULAR DISEASE (CARDIOLOGY),Y,CHILDREN'S HOSPITAL OF ORANGE COUNTY,ORANGE,CA,928684203

In [14]:
new_order = ['ZIP Code', 'State', 'City/Town','Primary Specialty', 'All Secondary Specialties', 'Gender', 'Facility Name', 'NPI', 'Provider Last Name','Provider First Name', 'Provider Middle Name']
df2_cleaned = df2_cleaned[new_order]
df2_cleaned

,ZIP Code,State,City/Town,Primary Specialty,All Secondary Specialties,Gender,Facility Name,NPI,Provider Last Name,Provider First Name,Provider Middle Name
0,943041601,CA,PALO ALTO,PEDIATRIC MEDICINE,NaN,M,LPCH MEDICAL GROUP DIV OF LUCILE,1003829771,MEANEY,PETER,ANDREW
1,914025423,CA,PANORAMA CITY,PEDIATRIC MEDICINE,INFECTIOUS DISEASE,M,SOUTHERN CALIFORNIA PERMANENTE MEDICAL GROUP,1013128297,BRONSTEIN,DAVID,E
4,926041723,CA,IRVINE,PEDIATRIC MEDICINE,NaN,F,MEMORIALCARE MEDICAL FOUNDATION,1013907377,BAKER,MARNIE,NaN
5,928684203,CA,ORANGE,PEDIATRIC MEDICINE,CARDIOVASCULAR DISEASE (CARDIOLOGY),M,CHILDREN'S HOSPITAL OF ORANGE COUNTY,1013912054,SWENSSON,RICHARD,ERIC
6,928684203,CA,ORANGE,PEDIATRIC MEDICINE,CARDIOVASCULAR DISEASE (CARDIOLOGY),M,CHILDREN'S HOSPITAL OF ORANGE COUNTY,1013912674,RECTO,MICHAEL,R
...,...,...,...,...,...,...,...,...,...,...,...
870,943041601,CA,PALO ALTO,PEDIATRIC MEDICINE,INFECTIOUS DISEASE,M,LPCH MEDICAL GROUP DIV OF LUCILE,1982997417,PHAM,TRUNG,HOANG MINH
871,941432202,CA,SAN FRANCISCO,PEDIATRIC MEDICINE,EMERGENCY MEDICINE,M,UCSF MEDICAL GROUP BUSINESS SERVICES,1992091474,SHAAHINFAR,ASHKON,NaN
872,941432202,CA,SAN FRANCISCO,PEDIATRIC MEDICINE,NaN,M,UCSF MEDICAL GROUP BUSINESS SERVICES,1992725808,TANEL,RONN,EL
874,928333207,CA,FULLERTON,PEDIATRIC MEDICINE,INTERNAL MEDICINE,M,NaN,1992857239,FLORES,EDGAR,NaN
876,900275822,CA,LOS ANGELES,PEDIATRIC MEDICINE,HEMATOLOGY/ONCOLOGY,M,SOUTHERN CALIFORNIA PERMANENTE MEDICAL GROUP,1992872717,COOPER,ROBERT,M